<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Models\Perjalanan; // Import the Perjalanan model

class ClearAutoGeneratedNoSuratTugas extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:clear-auto-generated-no-surat-tugas';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Clears auto-generated "no_surat_tugas" values in the database, setting them to NULL if they match the auto-generated pattern.';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $this->info('Starting to clear auto-generated "no_surat_tugas" values...');

        $updatedCount = 0;
        // Pattern for auto-generated 'no_surat_tugas': ST-XXXX/YYYY
        // (e.g., ST-0001/2025, ST-0123/2024)
        $pattern = '/^ST-\d{4}\/\d{4}$/';

        Perjalanan::chunk(100, function ($perjalanans) use (&$updatedCount, $pattern) {
            foreach ($perjalanans as $perjalanan) {
                if ($perjalanan->no_surat_tugas !== null && preg_match($pattern, $perjalanan->no_surat_tugas)) {
                    $perjalanan->no_surat_tugas = null;
                    $perjalanan->save();
                    $updatedCount++;
                    $this->line("Updated Perjalanan ID: {$perjalanan->id} - 'no_surat_tugas' set to NULL.");
                }
            }
        });

        $this->info("Finished. Total {$updatedCount} records updated.");
    }
}
