<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Kendaraan;

class KendaraanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'nopol_kendaraan' => 'D 1841 D',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Kijang Innova 2.0 V',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2006',
                'nomor_rangka' => 'MHFXW43G764030762',
                'nomor_mesin' => '1TR6319485',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Hukum',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1814 A',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2005',
                'nomor_rangka' => 'MHFXW42G152040991',
                'nomor_mesin' => '1TR6126338',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Hukum',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1737 D',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2006',
                'nomor_rangka' => 'MHFFMREK36K013538',
                'nomor_mesin' => 'DB51267',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Hukum',
                'penggunaan' => 'Operasional BBH Unpad',
            ],
            [
                'nopol_kendaraan' => 'D 1131 F',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2007',
                'nomor_rangka' => 'MHFM1BA3J7K066027',
                'nomor_mesin' => 'DC57433',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Hukum',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'Z 1061 BC',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Suzuki Ertiga',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => '2017',
                'nomor_rangka' => 'MHYKZE81SHJ324319',
                'nomor_mesin' => 'K14BT1262447',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Hukum',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1876 A',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Kijang KF81 Krista',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2004',
                'nomor_rangka' => 'MHF11UF8140042553',
                'nomor_mesin' => '1RZ7042567',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Ekonomi dan Bisnis',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1814 B',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2005',
                'nomor_rangka' => 'MHFXW42G552040704',
                'nomor_mesin' => '1TR-6125085',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Ekonomi dan Bisnis',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1815 A',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Kijang Innova 2.0 E',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2005',
                'nomor_rangka' => 'MHFXW41G650010155',
                'nomor_mesin' => '1TR6126774',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Ekonomi dan Bisnis',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1835 C',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Kijang Innova 2.0 E',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2005',
                'nomor_rangka' => 'MHFXW41G150012198',
                'nomor_mesin' => '1TR-6171173',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Ekonomi dan Bisnis',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1742 D',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2006',
                'nomor_rangka' => 'MHFXW42G062059288',
                'nomor_mesin' => 'ITR6204841',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Ekonomi dan Bisnis',
                'penggunaan' => 'Operasional Prodi MM',
            ],
            [
                'nopol_kendaraan' => 'D 1229 C',
                'jenis_kendaraan' => 'SUV',
                'merk_type' => 'Suzuki Grand Vitara JLX',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2007',
                'nomor_rangka' => 'MHYJTE54V7J703918',
                'nomor_mesin' => 'J20AID209906',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Ekonomi dan Bisnis',
                'penggunaan' => 'Operasional Prodi DIM',
            ],
            [
                'nopol_kendaraan' => 'D 1792 F',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2011',
                'nomor_rangka' => 'MHFXW42G9B2194845',
                'nomor_mesin' => '1TR7144309',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Ekonomi dan Bisnis',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 7097 AT',
                'jenis_kendaraan' => 'Mikrobus',
                'merk_type' => 'Isuzu NLR 55B',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => '2018',
                'nomor_rangka' => 'MHCNLR55EJJ081396',
                'nomor_mesin' => 'M081396',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Ekonomi dan Bisnis',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1129 F',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Kijang Innova 2.0 V',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2007',
                'nomor_rangka' => 'MHFXW43G774036644',
                'nomor_mesin' => '1TR6464469',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Kedokteran',
                'penggunaan' => null,
            ],
            [
                'nopol_kendaraan' => 'D 1097 F',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Suzuki APV DLX',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2007',
                'nomor_rangka' => 'MHYGDN41V7J158157',
                'nomor_mesin' => 'G15AID162023',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Kedokteran',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1550 JL',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2007',
                'nomor_rangka' => 'MHFM1BA3J7K046280',
                'nomor_mesin' => 'DC25032',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Kedokteran',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1552 JL',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2007',
                'nomor_rangka' => 'MHFXW42G372094019',
                'nomor_mesin' => 'ITR6393994',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Kedokteran',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 7073 C',
                'jenis_kendaraan' => 'Mikrobus',
                'merk_type' => 'KIA Pregio SE',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2010',
                'nomor_rangka' => 'PNAKF5S03AG001981',
                'nomor_mesin' => 'J2549138',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Kedokteran',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1096 E',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Avanza 1.5 Veloz',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2012',
                'nomor_rangka' => 'MHKM1CA4JCK006979',
                'nomor_mesin' => 'DCS1125',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Kedokteran',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1412 AKT',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Kijang Zenix Q 2.0 AT HV',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => '2023',
                'nomor_rangka' => 'MHFABBAA3P0408542',
                'nomor_mesin' => 'M20ANA88560',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Kedokteran',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 7458 AT',
                'jenis_kendaraan' => 'Mikrobus',
                'merk_type' => 'Toyota Hiace Premio 2.8 MT',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => '2023',
                'nomor_rangka' => 'JTF2A9CPXP6004185',
                'nomor_mesin' => '1GD9251566',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Kedokteran',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1203 F',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2008',
                'nomor_rangka' => 'MHFXW42G282115427',
                'nomor_mesin' => '1TR6551939',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'FMIPA',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1695 F',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2010',
                'nomor_rangka' => 'MHFM1BA3JAK725241',
                'nomor_mesin' => 'DG66154',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'FMIPA',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1831 D',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2006',
                'nomor_rangka' => 'MHFN1BA3J6K011506',
                'nomor_mesin' => 'DB71960',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Pertanian',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1327 F',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2009',
                'nomor_rangka' => 'MHFM1BA3J9K705094',
                'nomor_mesin' => 'DB86000',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Pertanian',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1167 F',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Avanza 1.5 S',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2007',
                'nomor_rangka' => 'MHFM1CA4J7K007359',
                'nomor_mesin' => 'DAF8963',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Kedokteran Gigi',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1458 F',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Avanza 1.5 S',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2010',
                'nomor_rangka' => 'MHFM1CA4JAK032644',
                'nomor_mesin' => 'DBM6325',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Kedokteran Gigi',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 9948 A',
                'jenis_kendaraan' => 'Ambulance',
                'merk_type' => 'Isuzu Panther TBR 54',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2010',
                'nomor_rangka' => 'MHCTBR54BAK154880',
                'nomor_mesin' => 'E154880',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Kedokteran Gigi',
                'penggunaan' => null,
            ],
            [
                'nopol_kendaraan' => 'D 1827 A',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2010',
                'nomor_rangka' => 'MHFM1BA3JAK283183',
                'nomor_mesin' => 'DG74940',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Ilmu Budaya',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1885 D',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2007',
                'nomor_rangka' => 'MHFXW42G972094476',
                'nomor_mesin' => '1TR6396216',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Ilmu Budaya',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1806 A',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2005',
                'nomor_rangka' => 'MHFXW42G152037976',
                'nomor_mesin' => '1TR6112868',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'FISIP',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1806 B',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2005',
                'nomor_rangka' => 'MHFXW42G852036792',
                'nomor_mesin' => '1TR6107212',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'FISIP',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1833 D',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2006',
                'nomor_rangka' => 'MHFM1BA3J6K012826',
                'nomor_mesin' => 'DB73989',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'FISIP',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'Z 365 A',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2006',
                'nomor_rangka' => 'MHFM1BA3J6K003566',
                'nomor_mesin' => 'DB60076',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Psikologi',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1531 B',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Avanza 1.5 S',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2011',
                'nomor_rangka' => 'MHFM1CA44JBK056530',
                'nomor_mesin' => 'DCF7363',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Psikologi',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1202 F',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2008',
                'nomor_rangka' => 'MHFXW42G182118836',
                'nomor_mesin' => 'ITR6576160',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Peternakan',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1814 F',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Avanza 1.5 S',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2011',
                'nomor_rangka' => 'MHFM1CA4JBK053750',
                'nomor_mesin' => 'DCD1529',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Peternakan',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 8440 A',
                'jenis_kendaraan' => 'Pick Up',
                'merk_type' => 'Toyota Kijang KF60 Long',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2004',
                'nomor_rangka' => 'MHF31KF6040030681',
                'nomor_mesin' => '7K0710394',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Peternakan',
                'penggunaan' => null,
            ],
            [
                'nopol_kendaraan' => 'D 1463 A',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2004',
                'nomor_rangka' => 'MHFXW42G542011217',
                'nomor_mesin' => '1TR6023161',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Ilmu Komunikasi',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1022 D',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2006',
                'nomor_rangka' => 'MHFXW42G062059209',
                'nomor_mesin' => '1TR6204713',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Ilmu Komunikasi',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1096 F',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Suzuki APV DLX',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2007',
                'nomor_rangka' => 'MHYGDN41V7J157952',
                'nomor_mesin' => 'G15AID161841',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Ilmu Komunikasi',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 7132 AU',
                'jenis_kendaraan' => 'Mikrobus',
                'merk_type' => 'Toyota Hiace Commuter MT',
                'warna_tanda' => 'Putih',
                'tahun_pembuatan' => '2024',
                'nomor_rangka' => 'JTFST22PXR0047904',
                'nomor_mesin' => '1KDB194842',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Ilmu Komunikasi',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'Z 1396 CJ',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Daihatsu Xenia Attivo',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2012',
                'nomor_rangka' => 'MHKV1BA2JCKO23362',
                'nomor_mesin' => 'DL22928',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Keperawatan',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1128 F',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2007',
                'nomor_rangka' => 'MHFM1BA3J7K066803',
                'nomor_mesin' => 'DC58629',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Keperawatan',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1130 F',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2007',
                'nomor_rangka' => 'MHFM1BA3J7K066514',
                'nomor_mesin' => 'DC58061',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Keperawatan',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1132 F',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2007',
                'nomor_rangka' => 'MHFM1BA3J7K066163',
                'nomor_mesin' => 'DC57656',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'FPIK',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1416 F',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2009',
                'nomor_rangka' => 'MHFM1BA3J9K188872',
                'nomor_mesin' => 'DE69697',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'FPIK',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1026 F',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2007',
                'nomor_rangka' => 'MHFM1BA3J7K033145',
                'nomor_mesin' => 'DC04950',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'FTIP',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1322 F',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Avanza 1.5 S',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2009',
                'nomor_rangka' => 'MHFM1CA4J9K019507',
                'nomor_mesin' => 'DBD3786',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Farmasi',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1324 F',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Avanza 1.5 S',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2009',
                'nomor_rangka' => 'MHFM1CA4J9K019621',
                'nomor_mesin' => 'DBD4354',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Farmasi',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1321 F',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2009',
                'nomor_rangka' => 'MHFM1BA3J9K138352',
                'nomor_mesin' => 'DD83873',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Teknik Geologi',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1697 F',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2010',
                'nomor_rangka' => 'MHFM1BA3JAK725257',
                'nomor_mesin' => 'DG71982',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Teknik Geologi',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1459 F',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Avanza 1.5 S',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2010',
                'nomor_rangka' => 'MHFM1CA4JAK032803',
                'nomor_mesin' => 'DBM7103',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Sekolah Pasca Sarjana',
                'penggunaan' => 'Operasional Fakultas',
            ],
            [
                'nopol_kendaraan' => 'D 1740 D',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Kijang Innova 2.0 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2006',
                'nomor_rangka' => 'MHFXW42G562066754',
                'nomor_mesin' => 'ITR6255173',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'MWA',
                'penggunaan' => 'Operasional',
            ],
            [
                'nopol_kendaraan' => 'D 1 DUP',
                'jenis_kendaraan' => 'SUV',
                'merk_type' => 'Hyundai Palisade',
                'warna_tanda' => 'Hitam',
                'tahun_pembuatan' => '2021',
                'nomor_rangka' => 'MHFGW8EM2H1018338',
                'nomor_mesin' => '1TRA400658',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Rektor',
                'penggunaan' => null,
            ],
            [
                'nopol_kendaraan' => 'D 1320 F',
                'jenis_kendaraan' => 'Minibus',
                'merk_type' => 'Toyota Avanza 1.3 G',
                'warna_tanda' => 'Merah',
                'tahun_pembuatan' => '2009',
                'nomor_rangka' => 'MHFM1BA3J9K138351',
                'nomor_mesin' => 'DD83872',
                'jenis_bbm_default' => null,
                'lokasi_kendaraan' => 'Fakultas Teknik Geologi',
                'penggunaan' => 'Operasional Fakultas',
            ],
        ];

        foreach ($data as $item) {
            Kendaraan::create($item);
        }
    }
}
