<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Staf;

class StafSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'nama_staf' => 'Agus Sudrajat',
                'nip_staf' => '196903162019063001',
                'gol_pangkat' => 'I/b',
                'status' => 'NON PNS',
                'pendidikan_aktif' => 'SD',
                'tanggal_lahir' => '1969-03-16',
                'kartu_pegawai' => '',
                'status_kepegawaian' => 'Pegawai Tetap Non PNS',
                'tempat_lahir' => 'Bandung',
                'no_ktp' => '3204391603690004',
                'no_npwp' => '812278158445000',
                'no_bpjs_kesehatan' => '1341097929',
                'no_bpjs_ketenagakerjaan' => '19075174169',
                'no_telepon' => '85321120903',
                'email' => 'agus.sudrajat@unpad.ac.id',
                'alamat_rumah' => 'Kp situkuluwung Rt 001/011 desa panundaan Kec:ciwidey kab:Bandung Jawa barat',
                'rekening' => '435185362',
                'nama_bank' => 'BJB',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Ajat Sudrajat',
                'nip_staf' => '198212042016023001',
                'gol_pangkat' => 'II/c',
                'status' => 'NON PNS',
                'pendidikan_aktif' => 'SLTA',
                'tanggal_lahir' => '1982-12-04',
                'kartu_pegawai' => '',
                'status_kepegawaian' => 'Pegawai Tetap Non PNS',
                'tempat_lahir' => 'Bandung',
                'no_ktp' => '',
                'no_npwp' => '',
                'no_bpjs_kesehatan' => '',
                'no_bpjs_ketenagakerjaan' => '',
                'no_telepon' => '81214450265',
                'email' => '',
                'alamat_rumah' => '',
                'rekening' => '0072212762100',
                'nama_bank' => 'BJB',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Amar',
                'nip_staf' => '197311172005011001',
                'gol_pangkat' => 'III/b',
                'status' => 'PNS',
                'pendidikan_aktif' => 'SLTA',
                'tanggal_lahir' => '1973-11-17',
                'kartu_pegawai' => 'M.022305',
                'status_kepegawaian' => 'Pegawai Negeri',
                'tempat_lahir' => 'Cicalengka',
                'no_ktp' => '3273301711730003',
                'no_npwp' => '',
                'no_bpjs_kesehatan' => '39286023',
                'no_bpjs_ketenagakerjaan' => '',
                'no_telepon' => '85640319589',
                'email' => 'amar@unpad.ac.id',
                'alamat_rumah' => 'Jl.Dago Pojok/Tanggulan Rt 04 Rw 03 Bandung',
                'rekening' => '',
                'nama_bank' => '',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Amin',
                'nip_staf' => '196903132005011002',
                'gol_pangkat' => 'III/b',
                'status' => 'PNS',
                'pendidikan_aktif' => 'SLTA',
                'tanggal_lahir' => '1969-03-13',
                'kartu_pegawai' => 'M.022352',
                'status_kepegawaian' => 'Pegawai Negeri',
                'tempat_lahir' => 'Ciamis',
                'no_ktp' => '3273221303690005',
                'no_npwp' => '',
                'no_bpjs_kesehatan' => '57981925',
                'no_bpjs_ketenagakerjaan' => '',
                'no_telepon' => '81394920869',
                'email' => 'amin@unpad.ac.id',
                'alamat_rumah' => 'CIPAGALO GIRANG NO.46 RT.04 RW.06, KELURAHAN MARGASARI, KECAMATAN BUAHBATU, KOTA BANDUNG, 40286',
                'rekening' => '194837525',
                'nama_bank' => 'BNI',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Andri Zaenudin',
                'nip_staf' => '199201032018077001',
                'gol_pangkat' => '',
                'status' => 'Kontrak',
                'pendidikan_aktif' => 'D3',
                'tanggal_lahir' => '1992-01-03',
                'kartu_pegawai' => '',
                'status_kepegawaian' => 'Peg.Perjanjian Kerja',
                'tempat_lahir' => 'Sumedang',
                'no_ktp' => '3211110301920005',
                'no_npwp' => '852227000000000',
                'no_bpjs_kesehatan' => '30003071962',
                'no_bpjs_ketenagakerjaan' => '22047952027',
                'no_telepon' => '87827963565',
                'email' => 'andri24@unpad.ac.id',
                'alamat_rumah' => 'Babakan Bandung RT/RW 001/003, Kel. Kutamandiri, kec. Tanjungsari, kab. Sumedang',
                'rekening' => '0720875178',
                'nama_bank' => 'BNI',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Arman Mardiana',
                'nip_staf' => '198701082018077001',
                'gol_pangkat' => '',
                'status' => 'Kontrak',
                'pendidikan_aktif' => 'SLTA',
                'tanggal_lahir' => '1987-01-08',
                'kartu_pegawai' => '',
                'status_kepegawaian' => 'Peg.Perjanjian Kerja',
                'tempat_lahir' => 'Sumedang',
                'no_ktp' => '3211110801870004',
                'no_npwp' => '200311348444000',
                'no_bpjs_kesehatan' => '2856390603',
                'no_bpjs_ketenagakerjaan' => '22047952035',
                'no_telepon' => '81316316687',
                'email' => 'mardiana18@unpad.ac.id',
                'alamat_rumah' => 'Kp,sayang tengah,RT003/RW003,Desa, Cikancung,Kec, Cikancung,Kab,Bandung',
                'rekening' => '7204739220',
                'nama_bank' => 'BSI',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Asep Rahmat',
                'nip_staf' => '197909192018077001',
                'gol_pangkat' => '',
                'status' => 'Kontrak',
                'pendidikan_aktif' => 'SD',
                'tanggal_lahir' => '1979-09-19',
                'kartu_pegawai' => '',
                'status_kepegawaian' => 'Peg.Perjanjian Kerja',
                'tempat_lahir' => 'Sumedang',
                'no_ktp' => '3211151909790018',
                'no_npwp' => '206055477446000',
                'no_bpjs_kesehatan' => '462742211',
                'no_bpjs_ketenagakerjaan' => '22056860616',
                'no_telepon' => '85946168243',
                'email' => 'asep.rahmat16@unpad.ic.id',
                'alamat_rumah' => 'Dusun cileles Rt 002/006',
                'rekening' => '0720382376',
                'nama_bank' => 'BNI',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Asep Ruhiyat',
                'nip_staf' => '197607142007101001',
                'gol_pangkat' => 'III/a',
                'status' => 'PNS',
                'pendidikan_aktif' => 'SLTA',
                'tanggal_lahir' => '1976-07-14',
                'kartu_pegawai' => 'N.532744',
                'status_kepegawaian' => 'Pegawai Negeri',
                'tempat_lahir' => 'Sumedang',
                'no_ktp' => '3211181407760004',
                'no_npwp' => '344521836446000',
                'no_bpjs_kesehatan' => '39286113',
                'no_bpjs_ketenagakerjaan' => '0',
                'no_telepon' => '82295655933',
                'email' => 'a. ruhiyat@unpad.ac.id',
                'alamat_rumah' => 'Dusun bojong rt 002rw002 desa pada suka kab Sumedang',
                'rekening' => '194838664',
                'nama_bank' => 'BNI',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Asep Saepudin',
                'nip_staf' => '198411172016023001',
                'gol_pangkat' => 'III/a',
                'status' => 'NON PNS',
                'pendidikan_aktif' => 'S1',
                'tanggal_lahir' => '1984-11-17',
                'kartu_pegawai' => '',
                'status_kepegawaian' => 'Pegawai Tetap Non PNS',
                'tempat_lahir' => 'Bandung',
                'no_ktp' => '3204051711840002',
                'no_npwp' => '',
                'no_bpjs_kesehatan' => '1777518821',
                'no_bpjs_ketenagakerjaan' => '16061576118',
                'no_telepon' => '82120110496',
                'email' => 'asep18@unpad.ac.id',
                'alamat_rumah' => 'Kp. Jajawat RT 002 RW 001 Cileunyi Wetan Kec. Cileunyi Kab. Bandung',
                'rekening' => '0072212797100',
                'nama_bank' => 'BJB',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Asep Sony Gunawan',
                'nip_staf' => '197807012016023001',
                'gol_pangkat' => 'III/a',
                'status' => 'NON PNS',
                'pendidikan_aktif' => 'S1',
                'tanggal_lahir' => '1978-07-01',
                'kartu_pegawai' => '',
                'status_kepegawaian' => 'Pegawai Tetap Non PNS',
                'tempat_lahir' => 'Sumedang',
                'no_ktp' => '3211150000000000',
                'no_npwp' => '749691762446000',
                'no_bpjs_kesehatan' => '1514933987',
                'no_bpjs_ketenagakerjaan' => '3211150000000000',
                'no_telepon' => '81395741212',
                'email' => 'asep.sony.gunawan@unpad.ac.id',
                'alamat_rumah' => 'Sukamanah Rt01,/ Rw01 Jatinangor sumedang',
                'rekening' => '7201440607',
                'nama_bank' => 'BSI',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Asep Supriatna',
                'nip_staf' => '198007262018077001',
                'gol_pangkat' => '',
                'status' => 'Kontrak',
                'pendidikan_aktif' => 'S1',
                'tanggal_lahir' => '1980-07-26',
                'kartu_pegawai' => '',
                'status_kepegawaian' => 'Peg.Perjanjian Kerja',
                'tempat_lahir' => 'Sumedang',
                'no_ktp' => '3211162607800004',
                'no_npwp' => '',
                'no_bpjs_kesehatan' => '3105128441',
                'no_bpjs_ketenagakerjaan' => '22047951904',
                'no_telepon' => '81222993134',
                'email' => 'supriatna14@unpad.ac.id',
                'alamat_rumah' => 'Dsn.Ciherang Ds.Pasir biru Kec.Rancakalong',
                'rekening' => '0199355693',
                'nama_bank' => 'BNI',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Asep Toni Suryanto',
                'nip_staf' => '198502202018077001',
                'gol_pangkat' => '',
                'status' => 'Kontrak',
                'pendidikan_aktif' => 'SLTA',
                'tanggal_lahir' => '1985-02-20',
                'kartu_pegawai' => '',
                'status_kepegawaian' => 'Peg.Perjanjian Kerja',
                'tempat_lahir' => 'Sumedang',
                'no_ktp' => '3211152002850004',
                'no_npwp' => '',
                'no_bpjs_kesehatan' => '2287533745',
                'no_bpjs_ketenagakerjaan' => '22047952001',
                'no_telepon' => '895342296051',
                'email' => 'a.toni@unpad.ac.id',
                'alamat_rumah' => 'Dusun Dangdeur RT 02/012 Desa Mekargalih Kecamatan Jatinangor Kabupaten Sumedang',
                'rekening' => '0722545659',
                'nama_bank' => 'BNI',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Budiyono',
                'nip_staf' => '196807201990031005',
                'gol_pangkat' => 'III/b',
                'status' => 'PNS',
                'pendidikan_aktif' => 'SLTA',
                'tanggal_lahir' => '1968-07-20',
                'kartu_pegawai' => 'E.763747',
                'status_kepegawaian' => 'Pegawai Negeri',
                'tempat_lahir' => 'Bandung',
                'no_ktp' => '3273242007680001',
                'no_npwp' => '',
                'no_bpjs_kesehatan' => '10209',
                'no_bpjs_ketenagakerjaan' => '0',
                'no_telepon' => '811222068',
                'email' => 'budiyono@unpad.ac.id',
                'alamat_rumah' => 'Griya Caraka Blok G-89 Cisaranren endah Arcamanik Bandung RT08 RW05',
                'rekening' => '0194838187',
                'nama_bank' => 'BNI',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Bunyamin',
                'nip_staf' => '197411082016023001',
                'gol_pangkat' => 'II/c',
                'status' => 'NON PNS',
                'pendidikan_aktif' => 'SLTA',
                'tanggal_lahir' => '1974-11-08',
                'kartu_pegawai' => '',
                'status_kepegawaian' => 'Pegawai Tetap Non PNS',
                'tempat_lahir' => 'Tasikmalaya',
                'no_ktp' => '3206170811740001',
                'no_npwp' => '749883914425000',
                'no_bpjs_kesehatan' => '1422822576',
                'no_bpjs_ketenagakerjaan' => '16061573537',
                'no_telepon' => '81312559930',
                'email' => 'bunyamin@unpad.ac.id',
                'alamat_rumah' => 'Kp Galumpit Rt 005 Rw 002 Ds tarunajaya Kec Sukaraja Kab Tasikmalaya',
                'rekening' => '7193524208',
                'nama_bank' => 'BJB',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Caswinto',
                'nip_staf' => '198306182018077001',
                'gol_pangkat' => '',
                'status' => 'Kontrak',
                'pendidikan_aktif' => 'SLTA',
                'tanggal_lahir' => '1983-06-18',
                'kartu_pegawai' => '',
                'status_kepegawaian' => 'Peg.Perjanjian Kerja',
                'tempat_lahir' => 'Sumedang',
                'no_ktp' => '3211151806830008',
                'no_npwp' => '900677584446000',
                'no_bpjs_kesehatan' => '1478365402',
                'no_bpjs_ketenagakerjaan' => '22056860624',
                'no_telepon' => '8131257532',
                'email' => 'caswinto14@unpad.ac.id',
                'alamat_rumah' => 'cileles',
                'rekening' => '0721406547',
                'nama_bank' => 'BSI',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Cep Elang',
                'nip_staf' => '198303262018077001',
                'gol_pangkat' => '',
                'status' => 'Kontrak',
                'pendidikan_aktif' => 'D3',
                'tanggal_lahir' => '1983-03-26',
                'kartu_pegawai' => '',
                'status_kepegawaian' => 'Peg.Perjanjian Kerja',
                'tempat_lahir' => 'Sumedang',
                'no_ktp' => '3211152603830022',
                'no_npwp' => '363143702446000',
                'no_bpjs_kesehatan' => '3105129633',
                'no_bpjs_ketenagakerjaan' => '22047951946',
                'no_telepon' => '895326428482',
                'email' => 'C.elang@unpad.ac.id',
                'alamat_rumah' => 'Jl Sukawening RT 04 RW O6 hegarmanah jatinangor',
                'rekening' => '0141776888',
                'nama_bank' => 'BNI',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Cucun Hermana',
                'nip_staf' => '198811082018077001',
                'gol_pangkat' => '',
                'status' => 'Kontrak',
                'pendidikan_aktif' => 'SLTA Kejuruan',
                'tanggal_lahir' => '1988-11-08',
                'kartu_pegawai' => '',
                'status_kepegawaian' => 'Peg.Perjanjian Kerja',
                'tempat_lahir' => 'Sumedang',
                'no_ktp' => '3211150811880002',
                'no_npwp' => '',
                'no_bpjs_kesehatan' => '3105128845',
                'no_bpjs_ketenagakerjaan' => '22047951912',
                'no_telepon' => '82116851115',
                'email' => 'cucun.hermana14@unpad.ac.id',
                'alamat_rumah' => 'Dusun Margalaksana Rt 02 Rw 09 Desa Hegarmanah Kecamatan Jatinangor Kabupaten Sumedang 45363',
                'rekening' => '0720788194',
                'nama_bank' => 'BNI',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Dady Mulyana',
                'nip_staf' => '198112272016023001',
                'gol_pangkat' => 'II/c',
                'status' => 'NON PNS',
                'pendidikan_aktif' => 'SLTA',
                'tanggal_lahir' => '1981-12-27',
                'kartu_pegawai' => '',
                'status_kepegawaian' => 'Pegawai Tetap Non PNS',
                'tempat_lahir' => 'Bandung',
                'no_ktp' => '3273212712810004',
                'no_npwp' => '',
                'no_bpjs_kesehatan' => '1338773455',
                'no_bpjs_ketenagakerjaan' => '16061574543',
                'no_telepon' => '82115120506',
                'email' => 'dady.mulyana@unpad.ac.id',
                'alamat_rumah' => 'Jl. Ciparay no.81 RT02/RW04',
                'rekening' => '7173306517',
                'nama_bank' => 'BNI',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Dedi',
                'nip_staf' => '197412072008101001',
                'gol_pangkat' => 'II/d',
                'status' => 'PNS',
                'pendidikan_aktif' => 'SLTA',
                'tanggal_lahir' => '1974-12-07',
                'kartu_pegawai' => 'P.091026',
                'status_kepegawaian' => 'Pegawai Negeri',
                'tempat_lahir' => 'Bandung',
                'no_ktp' => '3273260712740001',
                'no_npwp' => '344538285429000',
                'no_bpjs_kesehatan' => '166678773',
                'no_bpjs_ketenagakerjaan' => '',
                'no_telepon' => '81321194174',
                'email' => 'dedi@unpad.ac.id',
                'alamat_rumah' => 'Cisaranten wetan RT/RW 004/006 Des. Cisaranten wetan Kec. Cinambo bandung',
                'rekening' => '0194694937',
                'nama_bank' => 'BNI',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Dedi Apendi',
                'nip_staf' => '197704032018077001',
                'gol_pangkat' => '',
                'status' => 'Kontrak',
                'pendidikan_aktif' => 'SLTA Kejuruan',
                'tanggal_lahir' => '1977-04-03',
                'kartu_pegawai' => '',
                'status_kepegawaian' => 'Peg.Perjanjian Kerja',
                'tempat_lahir' => 'Bandung',
                'no_ktp' => '3211150304770006',
                'no_npwp' => '',
                'no_bpjs_kesehatan' => '2961516453',
                'no_bpjs_ketenagakerjaan' => '22056860640',
                'no_telepon' => '89647166902',
                'email' => 'dediapendi487@gmail.com',
                'alamat_rumah' => 'Ds Hegarmanah Dusun Sukanegla Rt04/Re05 kec Jatinangor  Sumedang',
                'rekening' => '0720792520',
                'nama_bank' => 'BNI',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Egi wahyudi',
                'nip_staf' => '199704202018077001',
                'gol_pangkat' => '',
                'status' => 'Kontrak',
                'pendidikan_aktif' => 'SLTA',
                'tanggal_lahir' => '1997-04-20',
                'kartu_pegawai' => '',
                'status_kepegawaian' => 'Peg.Perjanjian Kerja',
                'tempat_lahir' => 'Sumedang',
                'no_ktp' => '3211112004970006',
                'no_npwp' => '852434091446000',
                'no_bpjs_kesehatan' => '462828611',
                'no_bpjs_ketenagakerjaan' => '22047952019',
                'no_telepon' => '895349164718',
                'email' => 'egi@unpad.ac.id',
                'alamat_rumah' => 'DSN. BABAKAN BANDUNG RT/RW 02/04 DESA KUTAMANDIRI KEC. TANJUNGSARI',
                'rekening' => '0721551641',
                'nama_bank' => 'BNI',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Ellen Supriatna',
                'nip_staf' => '198407072016023001',
                'gol_pangkat' => 'II/c',
                'status' => 'NON PNS',
                'pendidikan_aktif' => 'SLTA',
                'tanggal_lahir' => '1984-07-07',
                'kartu_pegawai' => '',
                'status_kepegawaian' => 'Pegawai Tetap Non PNS',
                'tempat_lahir' => 'Cicalengka',
                'no_ktp' => '3211110707840007',
                'no_npwp' => '665874665446000',
                'no_bpjs_kesehatan' => '1264312664',
                'no_bpjs_ketenagakerjaan' => '16061575946',
                'no_telepon' => '82117161312',
                'email' => 'ellboizjr@gmail.com',
                'alamat_rumah' => 'Sinarmulya rt 01 rw 02 desa kutamandiri kec tanjungsari',
                'rekening' => '320272017',
                'nama_bank' => 'BNI',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Endin Rukmana',
                'nip_staf' => '197808112019063001',
                'gol_pangkat' => 'I/b',
                'status' => 'NON PNS',
                'pendidikan_aktif' => 'SLTP',
                'tanggal_lahir' => '1978-08-11',
                'kartu_pegawai' => '',
                'status_kepegawaian' => 'Pegawai Tetap Non PNS',
                'tempat_lahir' => 'Sumedang',
                'no_ktp' => '3211111108780013',
                'no_npwp' => '749853982446000',
                'no_bpjs_kesehatan' => '463899328',
                'no_bpjs_ketenagakerjaan' => '',
                'no_telepon' => '82129139434',
                'email' => 'endin. rukmana@unpad.ac.id',
                'alamat_rumah' => 'Babakan Bandung RT002 RW004 Desa Kutamandiri Kecamatan Tanjungsari 45362',
                'rekening' => '435098116',
                'nama_bank' => 'BNI',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Engkos Nandang',
                'nip_staf' => '197212191994121001',
                'gol_pangkat' => 'III/b',
                'status' => 'PNS',
                'pendidikan_aktif' => 'SLTA',
                'tanggal_lahir' => '1972-12-19',
                'kartu_pegawai' => 'G.240599',
                'status_kepegawaian' => 'Pegawai Negeri',
                'tempat_lahir' => 'Sumedang',
                'no_ktp' => '3211221912720004',
                'no_npwp' => '',
                'no_bpjs_kesehatan' => '58001073',
                'no_bpjs_ketenagakerjaan' => '0',
                'no_telepon' => '81320094006',
                'email' => 'engkos.nandang@unpad.ac.id',
                'alamat_rumah' => 'Dusun galudra rt001/001 Desa galudra kec  cimalaka. Kab sumedang',
                'rekening' => '194838267',
                'nama_bank' => 'BNI',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Gugun Gunawan, S.S.',
                'nip_staf' => '198211262016023001',
                'gol_pangkat' => 'III/b',
                'status' => 'NON PNS',
                'pendidikan_aktif' => 'S1',
                'tanggal_lahir' => '1982-11-26',
                'kartu_pegawai' => '',
                'status_kepegawaian' => 'Pegawai Tetap Non PNS',
                'tempat_lahir' => 'Tasikmalaya',
                'no_ktp' => '3278091610810001',
                'no_npwp' => '706016185425000',
                'no_bpjs_kesehatan' => '1777519416',
                'no_bpjs_ketenagakerjaan' => '',
                'no_telepon' => '85318952320',
                'email' => 'gugun.gunawan@unpad.ac.id',
                'alamat_rumah' => 'Buana Cicalengka Raya Blok F3 No. 8, Narawita, Kec. Cicalengka, Kab. Bandung',
                'rekening' => '',
                'nama_bank' => '',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Hendi Rohendi',
                'nip_staf' => '198504232018077001',
                'gol_pangkat' => '',
                'status' => 'Kontrak',
                'pendidikan_aktif' => 'SLTA',
                'tanggal_lahir' => '1985-04-23',
                'kartu_pegawai' => '',
                'status_kepegawaian' => 'Peg.Perjanjian Kerja',
                'tempat_lahir' => 'Sumedang',
                'no_ktp' => '3211112304850003',
                'no_npwp' => '',
                'no_bpjs_kesehatan' => '1963246059',
                'no_bpjs_ketenagakerjaan' => '22047951961',
                'no_telepon' => '81322150730',
                'email' => 'hendiaska69@gmail.com',
                'alamat_rumah' => 'Dsn.awi surat  rt 005,rw 003 desa tanjungsari kec.tanjungsari',
                'rekening' => '0199392158',
                'nama_bank' => 'BNI',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Irwan Udaya',
                'nip_staf' => '197905302016023001',
                'gol_pangkat' => 'II/c',
                'status' => 'NON PNS',
                'pendidikan_aktif' => 'SLTA',
                'tanggal_lahir' => '1979-05-30',
                'kartu_pegawai' => '',
                'status_kepegawaian' => 'Pegawai Tetap Non PNS',
                'tempat_lahir' => 'Bandung',
                'no_ktp' => '',
                'no_npwp' => '',
                'no_bpjs_kesehatan' => '',
                'no_bpjs_ketenagakerjaan' => '',
                'no_telepon' => '81214804625',
                'email' => '',
                'alamat_rumah' => '',
                'rekening' => '0072212861100',
                'nama_bank' => 'BJB',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Isep Atang, S.Sos.',
                'nip_staf' => '197705162007011002',
                'gol_pangkat' => 'III/c',
                'status' => 'PNS',
                'pendidikan_aktif' => 'S1',
                'tanggal_lahir' => '1977-05-16',
                'kartu_pegawai' => 'N.397379',
                'status_kepegawaian' => 'Pegawai Negeri',
                'tempat_lahir' => 'Sumedang',
                'no_ktp' => '3273051605770002',
                'no_npwp' => '',
                'no_bpjs_kesehatan' => '55300004',
                'no_bpjs_ketenagakerjaan' => '0',
                'no_telepon' => '81320452000',
                'email' => 'isep@unpad.ac.id',
                'alamat_rumah' => 'Maleber Utara rt 06/06 kelurahan Maleber kecamata. Andir kota Bandung',
                'rekening' => '0194838686',
                'nama_bank' => 'BNI',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Iwan Ridwan Sampurna',
                'nip_staf' => '197411182018077001',
                'gol_pangkat' => '',
                'status' => 'Kontrak',
                'pendidikan_aktif' => 'SLTP',
                'tanggal_lahir' => '1974-11-18',
                'kartu_pegawai' => '',
                'status_kepegawaian' => 'Peg.Perjanjian Kerja',
                'tempat_lahir' => 'Sumedang',
                'no_ktp' => '3211151811740002',
                'no_npwp' => '',
                'no_bpjs_kesehatan' => '2465880175',
                'no_bpjs_ketenagakerjaan' => '22047951888',
                'no_telepon' => '#ERROR!',
                'email' => 'i.ridwan@unpad.ac.id',
                'alamat_rumah' => 'Dusun Ciawi RT 003/005 Desa Cikeruh Kec. Jatinangor Kab. Sumedang',
                'rekening' => '0605895392',
                'nama_bank' => 'BNI',
                'status_aplikasi' => 'Pengemudi',
            ],
            [
                'nama_staf' => 'Iwan Saeful Anwar',
                'nip_staf' => '198312172016023001',
                'gol_pangkat' => 'II/c',
                'status' => 'NON PNS',
                'pendidikan_aktif' => 'SLTA',
                'tanggal_lahir' => '1983-12-17',
                'kartu_pegawai' => '',
                'status_kepegawaian' => 'Pegawai Tetap Non PNS',
                'tempat_lahir' => 'Sumedang',
                'no_ktp' => '3211241712830002',
                'no_npwp' => '749985487446000',
                'no_bpjs_kesehatan' => '1777518808',
                'no_bpjs_ketenagakerjaan' => '16061575771',
                'no_telepon' => '81322670636',
                'email' => 'i.s.anwar@unpad.ac.id',
                'alamat_rumah' => 'Tomo RT 003 / RW 005',
                'rekening' => '',
                'nama_bank' => '',
                'status_aplikasi' => 'Pengemudi',
            ],
        ];

        foreach ($data as $item) {
            Staf::create($item);
        }
    }
}
